services:
    nginx: # this is just a compose identifier, not the actual name of the container.
        container_name: nginx
        build: # specifies how to build a custom image from a Dockerfile.
            context: ./requirements/nginx # is the folder where Docker looks for the Dockerfile and any files referenced in it.
            dockerfile: Dockerfile # tells Docker which file to use. If my file is called Dockerfile, this line is optional.
        image: nginx:inception # name and tag of the Docker image from which the container is created.
        env_file: .env # tells Docker Compose to load environment variables from .env and inject them into the container.
        ports:
            - "443:443" # "host port : container port".
        networks:
            - inception
        volumes:
            - wordpress:/var/www/html
        restart: on-failure # restarts the container in case of crash.

    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb:inception
        env_file: .env
        networks:
            - inception
        volumes:
            - db:/var/lib/mysql
        restart: on-failure

    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress:inception
        env_file: .env
        networks:
           - inception
        volumes:
            - wordpress:/var/www/html
        restart: on-failure


networks:
    inception:
        driver: bridge # standard network type for internal communication.


# volumes are like files in your computer that containers can read and write. It stores data, even after containers are deleted.
# we use volumes so we can manage this info ourselves. If Docker does it, we dont have access to it.
volumes:
    db:
        driver: local # uses Dockerâ€™s local storage driver.
        driver_opts:
            type: none # no special filesystem type.
            o: bind # creates/uses an existing folder (the name is below) that manages the volume, instead of being Docker the one to manage it.
            device: ./data/db # it will store all the database (posts, users, comments etc).

    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./data/wordpress